spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpahsop # shop 오타로 hsop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 앱 실행시점에 db 엔티티를 다시 재생성
    properties:
      hibernate:
#        show_sql: true  # 시스템 아웃
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug #logger로 출력
